version: "3"
services:
  scanner:
    build: .
    volumes:
      - ./conf/jble6lowpand.conf:/opt/jble6lowpand/jble6lowpand.conf
      - ./conf/data:/opt/jble6lowpand/data
      - /sys/kernel/debug/bluetooth/6lowpan_control:/opt/jble6lowpand/bin/6lowpan_control
    network_mode: host
    privileged: true
