#! /bin/sh
#  /etc/init.d/jble6lowpand

### BEGIN INIT INFO
# Provides:          jble6lowpand
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Short-Description: Starts the Bluetooth 6Lowpan service
# Description:       This file is used to start the daemon
#                    and should be placed in /etc/init.d
### END INIT INFO

# Author:   Joel Frazier <frazieje@gmail.com>
# Date:     11/02/2017

NAME="jble6lowpand"
DESC="Bluetooth 6Lowpan service"

# The path to Jsvc
EXEC="/usr/bin/jsvc"

# The path to the folder of the repository
FILE_PATH="/usr/local/$NAME"

# The path to the folder containing the java runtime
JAVA_HOME="/usr/lib/jvm/jdk-8-oracle-arm32-vfp-hflt"

# Our classpath including our jar file
CLASS_PATH="$FILE_PATH/build/libs/jble6lowpand-0.1.jar:$FILE_PATH/build/output/libs/commons-daemon-1.0.15.jar:$FILE_PATH/build/output/libs/slf4j-api-1.7.25.jar:$FILE_PATH/build/output/libs/logback-classic-1.2.3.jar:$FILE_PATH/build/output/libs/logback-core-1.2.3.jar"

# The fully qualified name of the class to execute
CLASS="com.spoohapps.jble6lowpand.ScanningDaemon"

# library path for jni
LOADLIB="$FILE_PATH/jni/libs/arm32"

# Any command line arguments to be passed to the our Java Daemon implementations init() method 
ARGS="-d 3000 -t 2000 -c 1000 -w $FILE_PATH/knowndevices.conf"

# The file that will contain our process identification number (pid) for other scripts/programs that need to access it.
PID="/var/run/$NAME.pid"

# System.out writes to this file...
LOG_OUT="$FILE_PATH/log/$NAME.out"

# System.err writes to this file...
LOG_ERR="$FILE_PATH/err/$NAME.err"

jsvc_exec()
{   
    cd $FILE_PATH
    hciconfig hci0 reset
    sleep 1
    $EXEC -home $JAVA_HOME -cp $CLASS_PATH -Djava.library.path=$LOADLIB -Djava.rmi.server.codebase=file:$FILE_PATH/ -outfile $LOG_OUT -errfile $LOG_ERR -pidfile $PID $1 $CLASS $ARGS
}

case "$1" in
    start)  
        echo "Starting the $DESC..."        

        # Start the service
        jsvc_exec
        
        echo "The $DESC has started."
    ;;
    stop)
        echo "Stopping the $DESC..."

        # Stop the service
        jsvc_exec "-stop"       
        
        echo "The $DESC has stopped."
    ;;
    restart)
        if [ -f "$PID" ]; then
            
            echo "Restarting the $DESC..."
            
            # Stop the service
            jsvc_exec "-stop"
            
            # Start the service
            jsvc_exec
            
            echo "The $DESC has restarted."
        else
            echo "Daemon not running, no action taken"
            exit 1
        fi
            ;;
    *)
    echo "Usage: /etc/init.d/$NAME {start|stop|restart}" >&2
    exit 3
    ;;
esac
