/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_spoohapps_jble6lowpand_NativeBle6LowpanIpspService */

#ifndef _Included_com_spoohapps_jble6lowpand_NativeBle6LowpanIpspService
#define _Included_com_spoohapps_jble6lowpand_NativeBle6LowpanIpspService
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_spoohapps_jble6lowpand_NativeBle6LowpanIpspService
 * Method:    scanDevicesInternal
 * Signature: (I)[Lcom/spoohapps/farcommon/model/EUI48Address;
 */
JNIEXPORT jobjectArray JNICALL Java_com_spoohapps_jble6lowpand_NativeBle6LowpanIpspService_scanDevicesInternal
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_spoohapps_jble6lowpand_NativeBle6LowpanIpspService
 * Method:    connectDevice
 * Signature: (Lcom/spoohapps/farcommon/model/EUI48Address;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_spoohapps_jble6lowpand_NativeBle6LowpanIpspService_connectDevice
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_spoohapps_jble6lowpand_NativeBle6LowpanIpspService
 * Method:    disconnectDevice
 * Signature: (Lcom/spoohapps/farcommon/model/EUI48Address;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_spoohapps_jble6lowpand_NativeBle6LowpanIpspService_disconnectDevice
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_spoohapps_jble6lowpand_NativeBle6LowpanIpspService
 * Method:    getConnectedDevices
 * Signature: ()[Lcom/spoohapps/farcommon/model/EUI48Address;
 */
JNIEXPORT jobjectArray JNICALL Java_com_spoohapps_jble6lowpand_NativeBle6LowpanIpspService_getConnectedDevices
  (JNIEnv *, jobject);

/*
 * Class:     com_spoohapps_jble6lowpand_NativeBle6LowpanIpspService
 * Method:    initializeDevice
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_spoohapps_jble6lowpand_NativeBle6LowpanIpspService_initializeDevice
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
